### ISSUE TITLE
New station map

### ISSUE THREAD

**Issue by Jacobthegamer070** [BeeStation/BeeStation-Hornet#6193]
The new station Fland Station does not have a map, this is an issue for new players that just got this station selected.

**Comment by MNarath1** [comment]
https://affectedarc07.github.io/SS13WebMap/BeeStation/FlandStation/ litterally just click onto the map button on the beestation webside to get there

**Comment by KubeRoot** [comment]
Sounds like the map json should have `"map_link": "FlandStation",` so the map verb directs you there.

**Comment by MNarath1** [comment]
> Sounds like the map json should have `"map_link": "FlandStation",` so the map verb directs you there.

Speaking of the map verb in game where is it even hidden now can't seem to find it for over a year now. In the tgui tab.

**Comment by KubeRoot** [comment]
> where is it even

Quick code check suggests the OOC tab

```dm
/client/verb/map()
	set name = "View Webmap"
	set desc = "View the current map in the webviewer"
	set category = "OOC"
```

**Comment by DatBoiTim** [comment]
@KubeRoot it has been brought to my attention that this is resolved.

**Comment by KubeRoot** [comment]
Doesn't seem to be resolved, https://github.com/BeeStation/BeeStation-Hornet/blob/master/_maps/flandstation.json still doesn't have a `map_link`.
